//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.EmpTypes = new HashSet<EmpType>();
        }
    
        public short CatID { get; set; }
        public string CatName { get; set; }
        public Nullable<short> CompanyID { get; set; }
    
        public virtual ICollection<EmpType> EmpTypes { get; set; }
    }
}
