//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LvQuota
    {
        public int EmpID { get; set; }
        public double A { get; set; }
        public Nullable<double> TA { get; set; }
        public double B { get; set; }
        public Nullable<double> TB { get; set; }
        public double C { get; set; }
        public Nullable<double> TC { get; set; }
        public Nullable<double> D { get; set; }
        public Nullable<double> TD { get; set; }
        public Nullable<double> E { get; set; }
        public Nullable<double> TE { get; set; }
        public Nullable<double> F { get; set; }
        public Nullable<double> TF { get; set; }
        public Nullable<double> G { get; set; }
        public Nullable<double> TG { get; set; }
        public Nullable<double> H { get; set; }
        public Nullable<double> TH { get; set; }
        public Nullable<double> I { get; set; }
        public Nullable<double> TI { get; set; }
        public Nullable<double> J { get; set; }
        public Nullable<double> TJ { get; set; }
        public Nullable<double> K { get; set; }
        public Nullable<double> TK { get; set; }
        public Nullable<double> L { get; set; }
        public Nullable<double> TL { get; set; }
        public Nullable<short> CompanyID { get; set; }
    
        public virtual Emp Emp { get; set; }
    }
}
