//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmergencyDetail
    {
        public Nullable<int> EmpID { get; set; }
        public string DesignationName { get; set; }
        public string GradeName { get; set; }
        public string CompName { get; set; }
        public string JobTitle { get; set; }
        public string CityName { get; set; }
        public string RegionName { get; set; }
        public string LocName { get; set; }
        public string CrewName { get; set; }
        public string TypeName { get; set; }
        public string CatName { get; set; }
        public string ShiftName { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public string SectionName { get; set; }
        public string DeptName { get; set; }
        public string DivisionName { get; set; }
        public Nullable<short> SafeLocID { get; set; }
        public Nullable<int> EmgID { get; set; }
        public int EmgDetailID { get; set; }
        public Nullable<bool> SafeStatus { get; set; }
        public Nullable<bool> Status { get; set; }
        public string EmgNo { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> CloseDateTime { get; set; }
        public Nullable<int> TotalPresent { get; set; }
        public Nullable<int> TotalMissing { get; set; }
        public Nullable<int> TotalSaved { get; set; }
        public string EmgName { get; set; }
        public Nullable<int> Expr1 { get; set; }
    }
}
