//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttProcessorScheduler
    {
        public int AttProcesserID { get; set; }
        public System.DateTime WhenToProcess { get; set; }
        public string PeriodTag { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public short CompanyID { get; set; }
        public short LocationID { get; set; }
        public short CatID { get; set; }
    
        public virtual AttProcessorScheduler AttProcessorScheduler1 { get; set; }
        public virtual AttProcessorScheduler AttProcessorScheduler2 { get; set; }
    }
}
