//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttProcessor
    {
        public int AttProcessorID { get; set; }
        public string PeriodTag { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<bool> ProcessingDone { get; set; }
        public Nullable<System.DateTime> WhenToProcess { get; set; }
        public string MonthPeriod { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<short> LocationID { get; set; }
        public Nullable<short> CatID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
        public virtual Location Location { get; set; }
    }
}
