//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyImage
    {
        public Nullable<short> CompanyID { get; set; }
        public byte[] CompanyImage1 { get; set; }
        public int ImageID { get; set; }
    }
}
