//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSafety
    {
        public short UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<byte> Role { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> DeactivationDate { get; set; }
    }
}
